version: 2.1

orbs:
  android: circleci/android@1.0.3
  slack: circleci/slack@4.4.4

jobs:
  build:
    executor:
      name: android/android-machine

    steps:
      - checkout

      - slack/notify:
          template: basic_success_1 
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

      #- android/run-tests:
      #    test-command: ./gradlew lint testDebug --continue

      # - run:
      #     name: Test build
      #     command: |
      #       ./gradlew assembleRelease

      # - store_artifacts:
      #         path: app/build/outputs/apk/
      #         destination: apks/
workflows:
  sample:
    jobs:
      - build: 
          context: slack-secrets