version: 2.1

orbs:
  android: circleci/android@1.0.3
  telegram: woltsu/telegram@0.0.9

jobs:
  build:
    executor:
      name: android/android-machine

    steps:
      - checkout
      - telegram/getme

      #- android/run-tests:
      #    test-command: ./gradlew lint testDebug --continue

      # - run:
      #     name: Test build
      #     command: |
      #       ./gradlew assembleRelease

      # - store_artifacts:
      #         path: app/build/outputs/apk/
      #         destination: apks/
workflows:
  sample:
    jobs:
      - build