version: 2.1

orbs:
  android: circleci/android@1.0.3
  slack: circleci/slack@4.4.4

jobs:
  build:
    executor:
      name: android/android-machine

    steps:
      - checkout

      - slack/notify:
          SLACK_ACCESS_TOKEN: xoxb-2761735606565-2766965716980-DeQ4V40BIcLT6WZC2eiIdZjX
          template: basic_success_1 
          channel: $quizapp 

      #- android/run-tests:
      #    test-command: ./gradlew lint testDebug --continue

      # - run:
      #     name: Test build
      #     command: |
      #       ./gradlew assembleRelease

      # - store_artifacts:
      #         path: app/build/outputs/apk/
      #         destination: apks/
workflows:
  sample:
    jobs:
      - build: 
          context: slack-secrets